spring:
  application:
    name: meetnow
  data:
    mongodb:
      database: meetnow
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@meetnow.0of2r5k.mongodb.net/?retryWrites=true&w=majority&appName=Meetnow

server:
  port: 8891

logging:
  config: classpath:logback.xml

api:
  access-key: ${ACCESS_KEY_SECRET}