name: Deploy Meetnow API🚀

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.MEETNOW_DOCKER_HUB_ID }}
          password: ${{ secrets.MEETNOW_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd back
          docker build -t ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow-api:latest .
          docker push ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow-api:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.MEETNOW_SERVER_IP }}
          port: ${{ secrets.WONHYEONG_MAC_MINI_SSH_PORT }}
          username: ${{ secrets.WONHYEONG_MAC_MINI_USERNAME }}
          key: ${{ secrets.WONHYEONG_MAC_MINI_SSH_KEY }}
          script: |
            cd ${{ secrets.WONHYEONG_MAC_MINI_MEETNOW_HOME }}
            /opt/homebrew/bin/docker pull ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow-api:latest
            /opt/homebrew/bin/docker stop meetnow-api || true
            /opt/homebrew/bin/docker rm meetnow-api || true
            /opt/homebrew/bin/docker run -d --name meetnow-api -p 8891:8891 \
              --restart always \
              --network meetnow_app-network \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e MONGO_DB_USERNAME=${{ secrets.MEETNOW_MONGO_DB_USERNAME }} \
              -e MONGO_DB_PASSWORD=${{ secrets.MEETNOW_MONGO_DB_PASSWORD }} \
              -e ACCESS_KEY_SECRET=${{ secrets.ACCESS_KEY_SECRET }} \
              ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow-api:latest
            /opt/homebrew/bin/docker system prune -af
