name: Deploy Meetnow Web

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.MEETNOW_DOCKER_HUB_ID }}
        password: ${{ secrets.MEETNOW_DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        cd front
        docker build -t ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow:latest .
        docker push ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow:latest

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: meetnow.kr
        port: ${{ secrets.WONHYEONG_MAC_MINI_SSH_PORT }}
        username: ${{ secrets.WONHYEONG_MAC_MINI_USERNAME }}
        key: ${{ secrets.WONHYEONG_MAC_MINI_SSH_KEY }}
        script: |
          cd ${{ secrets.WONHYEONG_MAC_MINI_MEETNOW_HOME }}
          /usr/local/bin/docker pull ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow:latest
          /usr/local/bin/docker stop meetnow || true
          /usr/local/bin/docker rm meetnow || true
          /usr/local/bin/docker run -d --name meetnow -p 3000:3000 \
            --restart always \
            --network meetnow_app-network \
            ${{ vars.MEETNOW_DOCKER_HUB_ID }}/meetnow:latest
          /usr/local/bin/docker system prune -af